# Generated by Django 5.2.1 on 2025-05-27 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mango_pests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pestreport",
            name="affected_farm_area",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="pestreport",
            name="affected_stage",
            field=models.CharField(
                choices=[
                    ("Seedling", "Seedling"),
                    ("Vegatative", "Vegatative"),
                    ("Budding", "Budding"),
                    ("Flowering", "Flowering"),
                    ("Fruiting", "Fruiting"),
                    ("Maturity", "Maturity"),
                    ("Harvest", "Harvest"),
                ],
                default="Seedling",
            ),
        ),
        migrations.AddField(
            model_name="pestreport",
            name="date_obs",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pestreport",
            name="land_size",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AddField(
            model_name="pestreport",
            name="m_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="pestreport",
            name="severe_lvl",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="pestreport",
            name="symptoms",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="pestreport",
            name="image",
            field=models.ImageField(blank=True, upload_to="pests/images/"),
        ),
    ]
