# Generated by Django 5.2.1 on 2025-05-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mango_pests", "0003_rename_m_number_pestreport_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pestreport",
            old_name="date_obs",
            new_name="date_of_observation",
        ),
    ]
