# Generated by Django 5.2.1 on 2025-05-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests', '0004_rename_date_obs_pestreport_date_of_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('land_size', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='pestreport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pestreport',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='pestreport',
            name='land_size',
        ),
        migrations.RemoveField(
            model_name='pestreport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pestreport',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='pestreport',
            name='affected_stage',
            field=models.CharField(choices=[('Seedling', 'Seedling'), ('Vegatative', 'Vegatative'), ('Budding', 'Budding'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Maturity', 'Maturity'), ('Harvest', 'Harvest')], default='Seedling', max_length=20),
        ),
        migrations.AddField(
            model_name='pestreport',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mango_pests.farmer'),
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
