# Generated by Django 5.2.1 on 2025-05-27 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests', '0005_farmer_remove_pestreport_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='description',
        ),
        migrations.AddField(
            model_name='treatment',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='treatment',
            name='application_method',
            field=models.CharField(choices=[('Spray', 'Spray'), ('Soil drench', 'Soil drench'), ('Injection', 'Injection'), ('Manual removal', 'Manual removal')], default='Spray', max_length=50),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('Organic', 'Organic'), ('Chemical', 'Chemical'), ('Biological', 'Biological'), ('Mechanical', 'Mechanical')], default='Organic', max_length=50),
        ),
    ]
