# Generated by Django 5.2.1 on 2025-05-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests', '0006_rename_name_treatment_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='pest',
        ),
        migrations.AddField(
            model_name='treatment',
            name='pest_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='mango_pests.pestreport'),
        ),
    ]
