# Generated by Django 5.2.1 on 2025-05-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests', '0007_remove_treatment_pest_treatment_pest_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestreport',
            name='affected_stage',
            field=models.CharField(choices=[('Seedling', 'Seedling'), ('Vegetative', 'Vegetative'), ('Budding', 'Budding'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Maturity', 'Maturity'), ('Harvest', 'Harvest')], default='Seedling', max_length=20),
        ),
        migrations.AlterField(
            model_name='pestreport',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pest_reports', to='mango_pests.farmer'),
        ),
        migrations.AlterField(
            model_name='pestreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pests/images/'),
        ),
    ]
