# Generated by Django 5.2 on 2025-05-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango_pests', '0008_alter_pestreport_affected_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pestreport',
            old_name='affected_farm_area',
            new_name='affected_plant_number',
        ),
    ]
